### ISSUE TITLE
Unpaywall package - integrate with existing custom.js file

### ISSUE THREAD

**Issue by rmiessle** [bulib/primo-explore-bu#22]
Posted on gitter, didn't get a response, so trying here!

I've been messing around with the primo-explore-unpaywall package and was able to get it working via your instructions at #21 (thanks!). After getting it working with the plain vanilla view, I moved over all my files from our current live view into the primo-explore-devenv but it blows away all our code in custom.js ... any advice on how to get my existing custom.js code and the new package to play nice? I'm not particularly well-versed with AngularJS or NodeJS but can hack my way through things (and learning while doing it).

We're VE if it makes a difference in regard to how to packaging works.

https://gettysburg.primo.exlibrisgroup.com/discovery/search?vid=01GETTYSBURG_INST:MUSCAT&lang=en

**Comment by atla5** [comment]
**Potential Solution**: 
- Try **renaming the `custom.js` file** to `gettysburg.js` and rerunning it. 
- I **expect** that a new `custom.js` file should appear that contains the code from _both_ files.

**Explanation**: 
- when you run the `gulp create-package` or `gulp run` commands (without `--browserify`) the `primo-explore-devenv` tries to push all the javascript files it can find in `custom/VIEW_NAME/js/` into _one_ `custom.js` file.
- if there's only _one_ file in there already called `custom.js` you can't really see any changes and it doesn't look like it's doing much. but if there's _any_ other `*.js` file present without that name, it'll create a _new_ `custom.js` file with whatever's in the files it found, all added together that overwrites it
- renaming your existing `custom.js` file makes it so that when `primo-explore-devenv` looks for all the `*.js` files, it finds _both_ of them and puts _both_ of its contents into the new `custom.js` file instead of just overwriting your stuff.

Let me know if/how that works. And my apologies for not seeing your message on gitter! 😅

**Comment by rmiessle** [comment]
No problem on gitter, not in a big rush on this.

Renamed custom.js to gettyburg.js. When I run gulp run --browserify it only pulls in the code from main.js into new custom.js and custom.js.map files (and unpaywall works) ... this is what I was seeing before. If I omit --browserify it does combine the files, but it only concatenates main.js to the end of gettysburg.js and creates a new custom.js file from the two. This breaks.

So next experiment was to take all of the various bits out of gettysburg.js and paste them into main.js. This preserves the existing gettysburg.js code but it fouls up the app.component('prmSearchResultAvailabilityLineAfter') bit because we use Browzine and their custom.js additions injects their link here already. So it's not your code, it's a matter of trying to get the Browzine and Unpaywall bits to work well together in since they both want to live in the same area, which is eluding me.

Thanks for the help!

**Comment by atla5** [comment]
I'm more than happy to keep helping if/where I can.

### 1.  how to avoid copy/paste of `gettysburg.js` into the `main.js` file

Gotcha. When you use the `--browserify` flag it does something a bit more clever and looks for what's imported into the `main.js` file. 

You should be able to add the following line to top of your `main.js` file to get it to see that as well. let me know how that works:

```js
import './gettysburg.js';
```

### 2. the `prmSearchResultAvailabilityLineAfter` collision 

this is a bit more complicated. @elizoller had a similar problem that we worked on in [pull request 7](https://github.com/bulib/primo-explore-bu/pull/7). 

he might be able to help describe that process/reasoning a little better, or I can look at your code and try to help out as well. 

I _believe_ we started using that same method internally (at BU) as well to test the solution. That is available in our [`custom/BU/js/main.js`](https://github.com/bulib/primo-explore-devenv-bu/blob/master/custom/BU/js/main.js#L95) and looks like this: 

```js
.component('prmSearchResultAvailabilityLineAfter', {
    template: '<bulib-unpaywall></bulib-unpaywall>'
  })
```

**Comment by rmiessle** [comment]
Great, thanks for being willing to take a closer look and give me some pointers. I appreciate it! :)

I did a bit of research with the UMN code documentation for their HathiTrust package and I'm wondering if because the Browzine code isn't a module dependency, that may be what's causing the problem, but again, I don't know Angular well enough to know if/why/how that's the actual issue.

The Unpaywall code works on its own and matches what you've posted:

```
var app = angular.module('viewCustom', ['angularLoad', 'bulibUnpaywall']);

app.component('prmSearchResultAvailabilityLineAfter', {
    template: '<bulib-unpaywall></bulib-unpaywall>'
  })
```

The Browzine code that uses prmSearchResultAvailabilityLineAfter is:

```
  window.browzine = {
    api: "https://public-api.thirdiron.com/public/v1/libraries/xxx",
    apiKey: "xxx",
 
    journalCoverImagesEnabled: true,
 
    journalBrowZineWebLinkTextEnabled: true,
    journalBrowZineWebLinkText: "View Journal Contents",
 
    articleBrowZineWebLinkTextEnabled: true,
    articleBrowZineWebLinkText: "View Issue Contents",
 
    articlePDFDownloadLinkEnabled: true,
    articlePDFDownloadLinkText: "Download PDF",
 
    printRecordsIntegrationEnabled: true,
  };
 
  browzine.script = document.createElement("script");
  browzine.script.src = "https://s3.amazonaws.com/browzine-adapters/primo/browzine-primo-adapter.js";
  document.head.appendChild(browzine.script);
 
  app.controller('prmSearchResultAvailabilityLineAfterController', function($scope) {
    window.browzine.primo.searchResult($scope);
  });
 
  app.component('prmSearchResultAvailabilityLineAfter', {
    bindings: { parentCtrl: '<' },
    controller: 'prmSearchResultAvailabilityLineAfterController'
  });
```

The console error is:

```
angular.js:14516 Error: [$compile:multidir] Multiple directives [prmSearchResultAvailabilityLineAfter, prmSearchResultAvailabilityLineAfter] asking for new/isolated scope on: <prm-search-result-availability-line-after parent-ctrl="$ctrl">
http://errors.angularjs.org/1.6.3/$compile/multidir?p0=prmSearchResultAvailabilityLineAfter&p1=&p2=prmSearchResultAvailabilityLineAfter&p3=&p4=new%2Fisolated%20scope&p5=%3Cprm-search-result-availability-line-after%20parent-ctrl%3D%22%24ctrl%22%3E
```

**Comment by elizoller** [comment]
You have two components 'prmSearchResultAvailabilityLineAfter', angular forbids multiple directives with the same name. You might want to consider combining them since the naming of `prmSearchResultAvailabilityLineAfter` is significant to hook into the prm-after components which Primo provides. I eventually went my own way with the browzine code because we wanted to change how it acted and the look and feel but I essentially have one prmSearchResultAvailabilityLineAfter component. From your example you might be able to combine your two components into one like
```
app.component('prmSearchResultAvailabilityLineAfter', {
    bindings: { parentCtrl: '<' },
    controller: 'prmSearchResultAvailabilityLineAfterController',
    template: '<bulib-unpaywall></bulib-unpaywall>'
  });
```
as well as retaining all of the rest of the code (ie adding the bulib module and the browzine scripts). 
(That is untested by the way).

**Comment by rmiessle** [comment]
Thanks for jumping in! I tried doing that (and just did it again) and it throws the console error

```Error: [$injector:unpr] Unknown provider: eProvider <- e <- prmSearchResultAvailabilityLineAfterController```

The good thing is that this all may be moot for Browzine users, they are looking to implement the Unpaywall API into their service.

https://github.com/thirdiron/browzine-discovery-service-adapters/issues/70#issuecomment-589092142

**Comment by elizoller** [comment]
is there a trace to the line on that error message?

**Comment by rmiessle** [comment]
Here's the full error:

```
angular.js:14516 Error: [$injector:unpr] Unknown provider: eProvider <- e <- prmSearchResultAvailabilityLineAfterController
http://errors.angularjs.org/1.6.3/$injector/unpr?p0=eProvider%20%3C-%20e%20%3C-%20prmSearchResultAvailabilityLineAfterController
    at angular.js:66
    at angular.js:4789
    at Object.r [as get] (angular.js:4944)
    at angular.js:4794
    at r (angular.js:4944)
    at i (angular.js:4969)
    at Object.a [as invoke] (angular.js:4995)
    at f.instance (angular.js:10862)
    at p (angular.js:9726)
    at a (angular.js:9048)
```

**Comment by atla5** [comment]
Just checking in to make sure I'm in the loop. Has the problem been addressed? Is there anything more I can do to help?

**Comment by rmiessle** [comment]
I haven't been able to resolve. I am going to close this with the hope that Third Iron's new update to their LibKey service to add Unpaywall functionality will take care of it.

**Comment by atla5** [comment]
okay. sorry i couldn't be of more help! best of luck with LibKey. their stuff is awesome.
